# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 10:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('fbid', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Registered user',
                'verbose_name_plural': 'Registered users',
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField()),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_relationship', to='users.RegisteredUser')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_relationship', to='users.RegisteredUser')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('input_data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='TransactionBit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_owed_by_to_user', models.FloatField()),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_transaction_bit', to='users.RegisteredUser')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_transaction_bit', to='users.RegisteredUser')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Transaction')),
            ],
            options={
                'verbose_name': 'Transaction bit',
                'verbose_name_plural': 'Transaction bits',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='users',
            field=models.ManyToManyField(through='users.TransactionBit', to='users.RegisteredUser'),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='friends',
            field=models.ManyToManyField(through='users.Relationship', to='users.RegisteredUser'),
        ),
    ]
