# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160725_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='splitwise_email',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='splitwise_first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='splitwise_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='splitwise_last_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
